services:
  - type: web
    name: InsightFlow-AI-Streamlit
    runtime: python
    buildCommand: apt-get install -y tesseract-ocr && pip install -r requirements.txt
    startCommand: streamlit run app_streamlit.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: HF_HUB_DISABLE_SYMLINKS_WARNING
        value: 1