Requirement already satisfied: pytesseract in c:\users\g k\desktop\text-summarizer\venv\lib\site-packages (0.3.13)
Requirement already satisfied: Pillow in c:\users\g k\desktop\text-summarizer\venv\lib\site-packages (12.2.0)
services:
  - type: web
    name: TextGist-AI
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app_streamlit.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: HF_HUB_DISABLE_SYMLINKS_WARNING
        value: 1